

export const CART_ACTION_TYPES ={
    'SET_CART_ITEMS':'SET_CART_ITEMS',
    'TOGGLE_OPEN_CLOSE_CART':'TOGGLE_OPEN_CLOSE_CART'
}

export const USER_ACTION_TYPES ={
    'SET_CURRENT_USER': 'SET_CURRENT_USER'
}